/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaansmk;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atthoriq
 */
public class KonfirmasiHilang extends javax.swing.JFrame {
    public ResultSet rst;
    Connection CC = new koneksi().connect();
    public Statement stt;
    public DefaultTableModel tmdl;
    public PreparedStatement prst;
    String id;
    String idbuku;
    String noAnggota;
    String namaAngg;
    String tanggalpinjam;
    String judulbuku; 
    /**
     * Creates new form KonfirmasiHilang
     */
    public KonfirmasiHilang() {
        initComponents();
        judul();
        Datas("");
        kfa.setEnabled(false);
    }
    public void judul() {
            Object[] judul = {
        "id", "No Anggota ","Nama Peminjam","Id Buku", "Judul Buku", "Tanggal Pinjam", "Tenggat Kembali"
        };
        tmdl = new DefaultTableModel(null, judul);
        hilang.setModel(tmdl);}
    
    public void Datas(String idpem) {
        try {
            stt = CC.createStatement();
            tmdl.getDataVector().removeAllElements();
            tmdl.fireTableDataChanged();
            rst = stt.executeQuery("SELECT * FROM peminjam WHERE status = 5");
            
            while(rst.next()){
            Object[] data = {
                rst.getString("id"),
                rst.getString("noanggota"),
                rst.getString("Nama"),
                rst.getString("idbuku"),
                rst.getString("judulbuku"),
                rst.getString("tanggalpinjam"),
                rst.getString("tenggatkembali")
                
                
            };
            tmdl.addRow(data);
            }
            }catch(Exception e){
          e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kfa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tanggalkembali = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hilang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(199, 234, 238));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KONFIRMASI LAPORAN BUKU HILANG");
        jLabel1.setToolTipText("");

        kfa.setText("Konfirmasi");
        kfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kfaActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("TANGGAL SAAT INI");

        tanggalkembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tanggalkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalkembaliActionPerformed(evt);
            }
        });

        hilang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "No ANggota Peminjam", "Nama Peminjam", "id buku", "Judul Buku", "Tanggal Pinjam", "Tenggat Pengembalian"
            }
        ));
        hilang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hilangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hilang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kfa))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tanggalkembali)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(kfa))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kfaActionPerformed
        String hilang =("SELECT * FROM hilang WHERE idbuku = "+ idbuku +"  LIMIT 1" );
        try{
            prst = CC.prepareStatement(hilang);
            rst = prst.executeQuery();
            if(rst.next()){
                stt = CC.createStatement();
                stt.executeUpdate("UPDATE hilang Set jumlahhilang= jumlahhilang+1 Where hilang.idbuku = "+idbuku);
            }else{
                stt = CC.createStatement();
                stt.executeUpdate("INSERT INTO hilang(idbuku,judulbuku,noanggota,namaanggota,tanggalhilang, jumlahhilang) VALUES('"+ idbuku + "','"
                + judulbuku+ "','"
                + noAnggota + "','"
                + namaAngg + "','"
                + tanggalkembali.getText() + "',1)");
                stt = CC.createStatement();
                stt.executeUpdate("UPDATE buku Set sisabuku= sisabuku-1 Where buku.idbuku = "+id);
            }
            
            stt = CC.createStatement();
            stt.executeUpdate("INSERT INTO Denda(noanggota,namaanggota,namapetugas, sebabdenda, jumlah, status) VALUES('"+ noAnggota + "','"
            + namaAngg+ "','"
            + "Admin" + "','"
            + "Menghilangkan Buku Perpustakaan" + "','"
            + "50000" +"',"
            + "1" + ")");
            stt = CC.createStatement();
            stt.executeUpdate("INSERT INTO laporankembali VALUES('"+ id+ "','" 
                    + idbuku + "','"
                    + judulbuku + "','"
                    + noAnggota + "','"
                    + namaAngg + "','"
                    + tanggalpinjam + "','"
                    + tanggalkembali.getText() + "','Admin','Kembali' )");
            stt = CC.createStatement();
            stt.executeUpdate("UPDATE peminjam set "
                   + "tanggalkembali='" + tanggalkembali.getText() + "',"
                   + "petugaskonfirkembali='" + "Admin" + "',"
                   + "status = '4', keterangan = 'Hilang' WHERE peminjam.id = "+ id +  "" );
            Datas("");
            JOptionPane.showMessageDialog(null, "berhasil Dikonfirmasi");
            tanggalkembali.setText("");

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_kfaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        petugas_menu a = new petugas_menu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tanggalkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalkembaliActionPerformed

    private void hilangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hilangMouseClicked
        id = hilang.getValueAt(hilang.getSelectedRow(), 0).toString();
        idbuku = hilang.getValueAt(hilang.getSelectedRow(), 3).toString();
        judulbuku = hilang.getValueAt(hilang.getSelectedRow(), 4).toString();
        tanggalpinjam = hilang.getValueAt(hilang.getSelectedRow(), 5).toString();
        noAnggota = hilang.getValueAt(hilang.getSelectedRow(), 1).toString();
        namaAngg= hilang.getValueAt(hilang.getSelectedRow(), 2).toString();
        kfa.setEnabled(true);
    }//GEN-LAST:event_hilangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiHilang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiHilang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiHilang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiHilang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonfirmasiHilang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable hilang;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kfa;
    private javax.swing.JTextField tanggalkembali;
    // End of variables declaration//GEN-END:variables
}
